# RGB Matrix Controller Configuration - Optimized for 64x32 Matrix

matrix:
  # Matrix dimensions - 64x32 configuration
  rows: 32              # Number of rows (your matrix: 32)
  cols: 64              # Number of columns (your matrix: 64)
  
  # Chaining (for single panel)
  chain_length: 1       # Number of panels chained horizontally
  parallel: 1           # Number of parallel chains
  
  # Display settings optimized for 64x32
  brightness: 60        # Brightness level (0-100) - slightly higher for 64x32
  hardware_mapping: "adafruit-hat"  # Hardware mapping type
  
  # Advanced settings optimized for 64x32
  gpio_slowdown: 1      # GPIO slowdown (1 is usually fine for 64x32)
  pwm_bits: 11          # PWM bits (11 gives good color depth)
  pwm_lsb_nanoseconds: 130  # PWM LSB nanoseconds
  
  # 64x32 specific optimizations
  scan_mode: 0          # Scan mode (0 = progressive, 1 = interlaced)
  row_address_type: 0   # Row address type (0 = direct, 1 = AB-addressed)
  multiplexing: 0       # Multiplexing type (0 = direct, 1-11 = various types)

display:
  # Font settings optimized for 64x32 display
  default_font: "assets/fonts/6x10.bdf"  # Good size for 64x32
  small_font: "assets/fonts/4x6.bdf"     # For more text
  large_font: "assets/fonts/8x13.bdf"    # For emphasis
  
  # Animation settings
  scroll_speed: 0.03    # Slightly faster scroll for 64x32
  fade_speed: 0.02      # Fade transition speed
  
  # Color settings
  default_color: [255, 255, 255]  # Default text color (RGB)
  background_color: [0, 0, 0]     # Background color (RGB)
  
  # 64x32 specific display settings
  text_position:
    x: 1                # Default X position for text
    y: 10               # Default Y position for text (good for 32 row height)
  
  # Maximum characters that fit on 64x32 with 6x10 font
  max_chars_per_line: 10  # Approximately 10 characters with 6px wide font

web:
  # Web interface settings
  host: "0.0.0.0"       # Host to bind to (0.0.0.0 = all interfaces)
  port: 5000            # Port number
  debug: false          # Enable debug mode

weather:
  # Weather API settings (optional)
  api_key: "your_openweather_api_key_here"
  city: "San Francisco"
  units: "metric"       # metric, imperial, or kelvin
  update_interval: 600  # Update interval in seconds (10 minutes)
  
  # 64x32 weather display settings
  display_format: "compact"  # compact, detailed, icon_only
  show_temperature: true
  show_conditions: true
  show_humidity: false  # Skip humidity to save space on 64x32

clock:
  # Clock display settings optimized for 64x32
  format: "24h"         # 12h or 24h
  show_seconds: true    # Show seconds
  color: [0, 255, 0]    # Clock color (RGB)
  
  # 64x32 clock positioning
  position:
    x: 2                # X position for clock
    y: 16               # Y position for clock (centered vertically)
  
  # Clock formats that fit well on 64x32
  time_format: "%H:%M:%S"      # 24-hour with seconds
  date_format: "%m/%d"         # Short date format
  
news:
  # News ticker settings optimized for 64x32
  api_key: "your_news_api_key_here"
  sources: ["bbc-news", "reuters"]  # Fewer sources for faster updates
  update_interval: 1800 # Update interval in seconds (30 minutes)
  max_headlines: 3      # Fewer headlines for 64x32 display
  
  # 64x32 news display settings
  scroll_headlines: true
  max_headline_length: 80  # Truncate long headlines
  show_source: false       # Skip source to save space

# Power consumption estimates for 64x32 matrix
power:
  estimated_max_current: "4A"     # Maximum current draw at full white
  typical_current: "1.5A"         # Typical usage current
  recommended_supply: "5V 5A"     # Recommended power supply
  
# Performance settings for 64x32
performance:
  refresh_rate: 60      # Target refresh rate in Hz
  update_frequency: 30  # Display update frequency in Hz
  
# 64x32 specific examples and presets
presets:
  clock_large:
    font: "assets/fonts/8x13.bdf"
    position: [2, 20]
    color: [0, 255, 255]
  
  scrolling_text:
    font: "assets/fonts/6x10.bdf"
    position: [64, 10]  # Start from right edge
    color: [255, 255, 0]
    speed: 0.03
  
  weather_compact:
    font: "assets/fonts/4x6.bdf"
    position: [1, 8]
    color: [100, 200, 255]
